export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const USERPROFILEDATA = "USERPROFILEDATA";
export const USERPROFILEDATAUPDATE= "USERPROFILEDATAUPDATE";
export const NAVMENUDATAS = "NAVMENUDATAS";
export const GOOGLELANGUAGETRANSLATECODES = "GOOGLELANGUAGETRANSLATECODES";